events { worker_connections 1024; }

http {
    upstream node_app {
        # Switch traffic by changing active upstream server
        server app_blue:3000; # Blue environment
        # server app_green:3000; # Green environment
    }

    server {
        listen 80;

        location / {
            proxy_pass http://node_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}